blog/authapp/urls.py
from django.contrib import admin
from django.urls import path, include

from authapp.views import login, logout, register

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', register, name='register'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

blog/mainapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from mainapp.views import PostListView, PostDetailView, PostUserView, PostCreateView, PostUpdateView, PostDeleteView, \
    CategoryListView, PostsInCategoryDetailView, CategoryCreateView, AddPostToCategoryView, AddPostToCategoryListView, \
    CategoryUpdateView, CategoryDeleteView, post_search, contacts

app_name = 'mainapp'

urlpatterns = [
                  path('', PostListView.as_view(), name='home'),
                  path('post/<int:pk>/', PostDetailView.as_view(), name='post'),
                  path('posts/', PostUserView.as_view(), name='posts'),
                  path('categories/', CategoryListView.as_view(), name='categories'),
                  path('category/<int:pk>/', PostsInCategoryDetailView.as_view(), name='category'),
                  path('category_create/', CategoryCreateView.as_view(), name='category_create'),
                  path('updatecategory/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
                  path('deletecategory/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
                  path('create/', PostCreateView.as_view(), name='post_create'),
                  path('update/<int:pk>/', PostUpdateView.as_view(), name='post_update'),
                  path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
                  path('add_post_list/<int:pk>/', AddPostToCategoryListView.as_view(), name='add_post_list'),
                  path('add_post/<int:pk>/<int:cat_pk>/', AddPostToCategoryView.as_view(), name='add_post'),
                  path('search/', post_search, name='search'),
                  path('contacts/', contacts, name='contacts'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/mainapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    """Модель статьи"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    name = models.CharField(max_length=32, verbose_name='Название статьи')
    text = models.TextField(verbose_name='Текст статьи')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')
    is_active = models.BooleanField(default=True, verbose_name='Активна')
    picture = models.ImageField(upload_to='images', blank=True, verbose_name='Картинка')


class Category(models.Model):
    """Модель категории"""
    name = models.CharField(max_length=32, verbose_name='Название категории')
    description = models.CharField(max_length=128, blank=True, verbose_name='Описание категории')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    is_active = models.BooleanField(default=True, verbose_name='Активна')


class Tag(models.Model):
    """Модель тега"""
    name = models.CharField(max_length=32, verbose_name='Название тега')

    def __str__(self):
        return self.name


class PostToCategory(models.Model):
    """Связь статьи и категории"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Статья')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        unique_together = ('post', 'category')


class PostToTag(models.Model):
    """Связь статьи и тега"""
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Статья')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, verbose_name='Тег')

blog/mainapp/forms.py
from django import forms

from mainapp.models import Post, Category


class PostForm(forms.ModelForm):
    """Форма создания и изменения статьи"""
    class Meta:
        model = Post
        fields = ('name', 'text', 'picture',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class CategoryForm(forms.ModelForm):
    """Форма создания и изменения категории"""
    class Meta:
        model = Category
        fields = ('name', 'description',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class SearchForm(forms.Form):
    """Форма поиска по тегам"""
    tags = forms.CharField()


class ContactsForm(forms.Form):
    """Форма обратной связи"""
    name = forms.CharField()
    email = forms.EmailField()
    text = forms.Textarea()

blog/mainapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from mainapp.forms import PostForm, CategoryForm, SearchForm, ContactsForm
from mainapp.models import Post, Category, PostToCategory, Tag, PostToTag


class PostListView(ListView):
    """Представление для просмотра всех статей"""
    model = Post
    template_name = 'mainapp/index.html'
    ordering = ['-created_at']
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Home'
        return context


class PostDetailView(DetailView):
    """Представление для просмотра конкретной статьи"""
    model = Post
    context_object_name = 'post'
    template_name = 'mainapp/post.html'

    def get_context_data(self, **kwargs):
        """Добавление в context data тегов"""
        context = super().get_context_data(**kwargs)
        context['title'] = f'Blog | Post'
        context['tags'] = []
        try:
            for post_bind_tag in PostToTag.objects.filter(post_id=self.request.resolver_match[2]['pk']):
                context['tags'].append(Tag.objects.filter(pk=post_bind_tag.id)[0])
        except Exception as e:
            pass
        return context


class PostUserView(ListView):
    """Представление для отображения и редактирования статей текущего пользователя"""
    model = Post
    context_object_name = 'user_posts'
    ordering = ['-created_at']
    paginate_by = 10
    template_name = 'mainapp/posts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Posts'
        return context


class PostCreateView(CreateView):
    """Представление для создания статьи"""
    form_class = PostForm
    model = Post
    success_url = '/posts/'
    template_name = 'mainapp/post_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Create New Post'
        return context

    def post(self, request, *args, **kwargs):
        """Добавлено автоматическое заполнение поля user, добавление тегов/тега, если были указаны"""
        tags = self.request.POST['tags'].split('#')
        print(tags)
        try:
            post = Post.objects.create(user=self.request.user, name=self.request.POST['name'],
                                       text=self.request.POST['text'], picture=request._files['picture'])
        except Exception:
            post = Post.objects.create(user=self.request.user, name=self.request.POST['name'],
                                       text=self.request.POST['text'])
        post.save()
        for tag in tags:
            if tag != '':
                tag_obj = Tag.objects.create(name=tag)
                tag_obj.save()
                tag_bind_post = PostToTag.objects.create(post=post, tag=tag_obj)
                tag_bind_post.save()

        return HttpResponseRedirect('/posts/')

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PostUpdateView(UpdateView):
    """Представление для изменения статьи"""
    form_class = PostForm
    model = Post
    success_url = '/posts/'
    template_name = 'mainapp/post_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Update'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PostDeleteView(DeleteView):
    """Представление для удаления статьи"""
    model = Post
    success_url = '/posts/'
    template_name = 'mainapp/post_delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CategoryListView(ListView):
    """Представление для просмотра категорий"""
    model = Category
    template_name = 'mainapp/categories.html'
    context_object_name = 'categories'
    ordering = ['-created_at']
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Categories'
        return context


class CategoryCreateView(CreateView):
    """Создание категорий"""
    form_class = CategoryForm
    model = Category
    success_url = '/categories/'
    template_name = 'mainapp/category_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Create New Category'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_authenticated))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CategoryUpdateView(UpdateView):
    """Изменение категорий"""
    form_class = CategoryForm
    model = Category
    success_url = '/categories/'
    template_name = 'mainapp/category_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Update'
        return context

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class CategoryDeleteView(DeleteView):
    """Удаление категорий"""
    model = Category
    success_url = '/categories/'
    template_name = 'mainapp/category_delete.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class PostsInCategoryDetailView(DetailView):
    """Просмотр статей в конкретной категории"""
    model = Category
    context_object_name = 'category'
    template_name = 'mainapp/category.html'
    ordering = ['-created_at']
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Blog | Category'
        context['data'] = PostToCategory.objects.filter(category_id=self.request.__dict__['resolver_match'][2]['pk'])
        return context


class AddPostToCategoryListView(ListView):
    """Просмотр статей для добавления в выбранную категорию"""
    model = Post
    success_url = '/categories/'
    context_object_name = 'posts'
    ordering = ['-created_at']
    paginate_by = 10
    template_name = 'mainapp/post_to_category.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Add To Category'
        context['category'] = self.request.__dict__['resolver_match'][2]['pk']
        return context


class AddPostToCategoryView(ListView):
    """Добавление выбранной статьи в выбранную категорию"""
    model = PostToCategory
    success_url = '/categories/'
    context_object_name = 'posts_to_category'
    # ordering = ['-created_at']
    paginate_by = 10
    template_name = 'mainapp/add_post.html'

    def get_context_data(self, **kwargs):
        pk_data = self.request.__dict__['resolver_match'][2]
        context = super().get_context_data(**kwargs)
        context['title'] = 'Blog | Add Post'

        try:
            added_post = PostToCategory.objects.create(post_id=pk_data['pk'], category_id=pk_data['cat_pk'])
            added_post.save()
        except Exception:
            context['data'] = 'Статья уже в этой категории'
        return context


def post_search(request):
    """Поиск по тегам"""
    form = SearchForm()
    tags = None
    results = []
    if 'tags' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            tags = form.cleaned_data['tags'].split('#')
            for tag in tags:
                if tag != '':
                    try:
                        for tag in Tag.objects.filter(name=tag):
                            results.append(PostToTag.objects.filter(tag_id=tag)[0])
                    except Exception as e:
                        pass

    return render(request,
                  'mainapp/search.html',
                  {'form': form,
                   'query': tags,
                   'results': results})


def contacts(request):
    """Представление для обратной связи"""
    form = ContactsForm()
    results = request.GET
    print(results)  # имитация обратной связи

    return render(request,
                  'mainapp/contacts.html',
                  {'form': form,
                   'results': results})

blog/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ title }}</title>
</head>
<body style="background-color: rgba(173,255,105,0.4)">
{% include 'mainapp/top.html' %}
<div class="container">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

blog/mainapp/templates/mainapp/category.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2>{{ category.name }}</h2>
        <p style="text-align: left">{{ category.description }}</p>
        <br>
        <a href="{% url 'mainapp:add_post_list' category.id %}">Добавить статью в категорию "{{ category.name }}"</a>
        <br>
        <ul>
            {% for post in data %}
                <li>
                    <a href="{% url 'mainapp:post' post.post.id %}">{{ post.post.name }}</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'mainapp:home' %}">Домой</a>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/category_create.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2>Создание категории</h2>
        <hr>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Создать категорию">
            <a href="{% url 'mainapp:categories' %}">Отмена</a>
        </form>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/category_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div></div>
    <div>
        <h2>Удаление категории "{{ category.name }}"</h2>
        <hr>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Удалить">
            <a href="{% url 'mainapp:categories' %}">Отмена</a>
        </form>
    </div>
    <div></div>
{% endblock %}

blog/mainapp/templates/mainapp/category_update.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2>Редактироваие категории</h2>
        <hr>
        <form action="" method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Обновить">
            <a href="{% url 'mainapp:categories' %}">Отмена</a>
        </form>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    {% if results %}
        <div>
            <h2>
                Ваше сообщение отправлено
            </h2>
        </div>
    {% else %}
        <h1>Напишите нам</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Отправить">
        </form>
        <br>
    {% endif %}
{% endblock %}

blog/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        {% if post_list %}
            <form action="" method="post">
                {% csrf_token %}
                {% for post in post_list %}
                    <div>
                        <div>
                            <ul style="display: flex; justify-content: space-around; list-style-type: none; font-size: large; font-style: italic; font-weight: bold;">
                                <li style="display: inline;">"{{ post.name }}";</li>
                                <li style="display: inline;">автор: {{ post.user }};</li>
                                <li style="display: inline;">дата создания: {{ post.created_at }}</li>
                            </ul>
                        </div>
                        <hr>
                        <div>
                            <p style="word-wrap: break-word;">{{ post.text | truncatewords:70 }}
                                <a href="{% url 'mainapp:post' post.id %}">Читать далее</a>
                            </p>
                        </div>
                    </div>
                    <hr>
                    <hr>
                {% endfor %}
            </form>
        {% else %}
            <h2>Нет статей</h2>
        {% endif %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">Предыдущая</a></li>
                {% endif %}
                <li class="page-item"><span
                        class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/post.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2>{{ post.name }}</h2>
        <p style="text-align: left">{{ post.text }}</p>
        {% if post.picture %}
            <img src="/media/{{ post.picture }}" alt="post picture">
        {% endif %}
        <br>
        <ul>
            {% for tag in tags %}
                <li>
                    <a href="{% url 'mainapp:search' %}?tags={{ tag }}">#{{ tag }}</a>
                </li>
            {% endfor %}
        </ul>
        <a href="{% url 'mainapp:home' %}">Домой</a>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/post_create.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2>Создание статьи</h2>
        <hr>
        <form action="" method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <label>
                <input type="text" name="tags" placeholder="#tag1#tag2#tag3">
            </label><label> Добавить теги</label>
            <br>
            <br>
            <input type="submit" value="Создать статью">
            <a href="{% url 'mainapp:home' %}">Отмена</a>
        </form>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/post_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div></div>
    <div>
        <h2>Удаление статьи "{{ post.name }}"</h2>
        <hr>
        <form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Удалить">
            <a href="{% url 'mainapp:posts' %}">Отмена</a>
        </form>
    </div>
    <div></div>
{% endblock %}

blog/mainapp/templates/mainapp/post_to_category.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2>Мои статьи</h2>
        <form action="" method="post">
            {% csrf_token %}
            {% if posts %}
                <table>
                    <thead>
                    <tr>
                        <th scope="col" style="border: 2px solid black;">Название</th>
                        <th scope="col" style="border: 2px solid black;">Автор</th>
                        <th scope="col" style="border: 2px solid black;">Текст статьи</th>
                        <th scope="col" style="border: 2px solid black;">Действия</th>
                    </tr>
                    </thead>
                    {% for post in posts %}
                        {% if post.user == user %}
                            <tbody>
                            <tr>
                                <td style="border: 2px solid black;">{{ post.name }}</td>
                                <td style="border: 2px solid black;">{{ post.user }}</td>
                                <td style="border: 2px solid black;">{{ post.text | truncatewords:50 }} </td>
                                <td style="border: 2px solid black;">
                                    <form action="#" method="post">
                                        <a href="{% url 'mainapp:add_post' post.id category%}">Добавить в категорию</a>
                                    </form>
                                </td>
                            </tr>
                            </tbody>
                        {% endif %}
                    {% endfor %}
                </table>
                </form>
                <hr>
            {% else %}
                <h2>Нет статей</h2>
            {% endif %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                {% endif %}
                <li class="page-item"><span
                        class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/posts.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h2>Мои статьи</h2>
        <form action="" method="post">
            {% csrf_token %}
            <a href="{% url 'mainapp:post_create' %}">Добавить статью</a>
            {% if user_posts %}
                <table>
                    <thead>
                    <tr>
                        <th scope="col" style="border: 2px solid black;">Название</th>
                        <th scope="col" style="border: 2px solid black;">Автор</th>
                        <th scope="col" style="border: 2px solid black;">Текст статьи</th>
                        <th scope="col" style="border: 2px solid black;">Действия</th>
                    </tr>
                    </thead>
                    {% for update in user_posts %}
                        {% if update.user == user %}
                            <tbody>
                            <tr>
                                <td style="border: 2px solid black;">{{ update.name }}</td>
                                <td style="border: 2px solid black;">{{ update.user }}</td>
                                <td style="border: 2px solid black;">{{ update.text | truncatewords:50 }} </td>
                                <td style="border: 2px solid black;">
                                    <form action="#" method="post">
                                        <a href="{% url 'mainapp:post_update' update.id %}">Изменить</a>
                                        <a href="{% url 'mainapp:post_delete' update.id %}">Удалить</a>
                                    </form>
                                </td>
                            </tr>
                            </tbody>
                        {% endif %}
                    {% endfor %}
                </table>
                </form>
                <hr>
            {% else %}
                <h2>Нет статей</h2>
            {% endif %}
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                {% endif %}
                <li class="page-item"><span
                        class="page-link">Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}</span>
                </li>
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Следующая</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock %}

blog/mainapp/templates/mainapp/search.html
{% extends "mainapp/base.html" %}

{% block content %}
    <h1>Поиск статей по тегам</h1>
    <form action="." method="get">
        {{ form.as_p }}
        <input type="submit" value="Поиск">
    </form>
    <br>
    {% if results %}
        {% for result in results %}
            <a href="{% url 'mainapp:post' result.id %}">{{ result.post.name }}</a>
            <br>
        {% endfor %}
    {% elif query %}
        Поиск не дал результатов
    {% endif %}
{% endblock %}

blog/mainapp/templates/mainapp/top.html
<nav class="top" style="padding-bottom: 20px;">
    <div style=" background-color: rgba(60,255,22,0.58)">
        <hr>
        <ul style="display: flex; justify-content: space-evenly; font-size: large; font-weight: bold;">
            <li>
                <a href="{% url 'mainapp:home' %}">Главная</a>
            </li>
            <li>
                <a href="{% url 'mainapp:categories' %}">Категории</a>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'mainapp:posts' %}">Мои статьи</a>
                </li>
            {% endif %}
            <li>
                <a href="{% url 'mainapp:search' %}">Поиск по тегам</a>
            </li>
            <li>
                <a href="{% url 'mainapp:contacts' %}">Обратная связь</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a>
                        {{ user.username|default:'Пользователь' }}
                    </a>
                </li>
            {% endif %}
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'authapp:logout' %}">Выйти</a>
                {% else %}
                    <a class="nav-link" href="{% url 'authapp:login' %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'authapp:register' %}">Зарегистрироваться</a>
                    </li>
                {% endif %}
        </ul>
        <hr>
    </div>
</nav>